# Generated by Django 4.0.4 on 2022-05-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('cover_image_url', models.CharField(max_length=300)),
                ('genre', models.CharField(choices=[('AC', 'Action'), ('AD', 'Adventure'), ('CO', 'Comedy'), ('CR', 'Crime'), ('DR', 'Drama'), ('FA', 'Fantasy'), ('HO', 'Horror'), ('MY', 'Mystery'), ('RO', 'Romance'), ('TH', 'Thiller')], default='CO', max_length=2)),
            ],
        ),
    ]
