# Generated by Django 4.0.4 on 2022-06-04 13:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0002_alter_movie_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='dislikes',
            field=models.ManyToManyField(related_name='movies_disliked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='movie',
            name='likes',
            field=models.ManyToManyField(related_name='movies_liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
