# Generated by Django 4.0.4 on 2022-06-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_remove_movie_dislikes_remove_movie_likes_movielike'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='movielike',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
