# Generated by Django 4.0.4 on 2022-06-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_id_alter_movielike_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='number_of_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
