# Generated by Django 4.0.4 on 2022-06-07 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_movie_dislikes_movie_likes_alter_movie_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieLike',
        ),
    ]
